# Generated by Django 4.2 on 2026-03-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementpreferences',
            name='role',
        ),
    ]
