# Generated by Django 5.2.6 on 2025-10-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdetails',
            name='course',
        ),
    ]
