# Generated by Django 4.2 on 2026-02-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usertype_delete_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
