# Generated by Django 5.2.6 on 2025-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='company_logos/')),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('domain', models.CharField(max_length=200, null=True)),
                ('package', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-time'), ('internship', 'Internship'), ('part-time', 'Part-time')], default='full-time', max_length=20, null=True)),
                ('work_mode', models.CharField(choices=[('on-site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on-site', max_length=20, null=True)),
            ],
        ),
    ]
