# Generated by Django 4.2 on 2026-02-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='company_logos/')),
                ('company_url', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('required_Skills', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-time'), ('internship', 'Internship'), ('part-time', 'Part-time')], default='full-time', max_length=20, null=True)),
                ('work_mode', models.CharField(choices=[('on-site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on-site', max_length=20, null=True)),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('domain', models.CharField(max_length=200, null=True)),
                ('package', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('experience', models.CharField(max_length=20, null=True)),
                ('vaccacy_no', models.IntegerField(null=True)),
                ('min_gpa', models.CharField(max_length=20, null=True)),
                ('passing_year', models.CharField(max_length=30, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Placement_details',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='placement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='placement.placement'),
        ),
    ]
