# Generated by Django 4.2 on 2026-02-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_company_jobdetails_placement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='required_Skills',
            new_name='required_skills',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='vaccacy_no',
            new_name='vacancy_no',
        ),
    ]
