# Generated by Django 4.2 on 2026-02-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_rename_required_skills_jobdetails_required_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
