# Generated by Django 4.2 on 2026-03-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_alter_company_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='placement.company'),
        ),
    ]
