# Generated by Django 4.2 on 2025-11-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0002_alter_account_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
